import { chromium } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
const OUT = '/private/var/folders/pw/zr39lg6537l37bwc6gtzs0780000gn/T/opencode/pagination-debug';
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const logs = [];
page.on('console', m => { const t = m.text(); if (t.includes('[paginate]')) logs.push(`[${m.type()}] ${t}`); });
await page.goto('http://127.0.0.1:5176/', { waitUntil: 'networkidle' });
await page.locator('.para .tok').first().waitFor({ timeout: 20000 });
await page.waitForTimeout(600);
const EN_SENT = 'Time and people find a way through the garden where the small cat drinks milk and the big dog likes fish while birds sing songs in the morning sun ';
const paras = [];
for (let i = 0; i < 10; i++) paras.push(`Paragraph ${i + 1}. ` + EN_SENT.repeat(3));
await page.getByRole('button', { name: '📚 书架', exact: true }).click();
await page.locator('.card select').first().selectOption('en');
await page.locator('[data-testid="paste-input"]').fill(paras.join('\n\n'));
await page.locator('[data-testid="paste-import"]').click();
await page.getByRole('button', { name: '📖 阅读', exact: true }).click();
await page.locator('.para .tok').first().waitFor({ timeout: 20000 });
await page.waitForTimeout(3000);
writeFileSync(OUT + '/probe-log.txt', logs.join('\n'));
console.log('saved', logs.length, 'lines');
await browser.close();
